import type { Metadata } from "next";
import "./globals.css";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/UI/lib";
import { Toaster } from "@/UI/components/ui/sonner";
import QueryClientProvider from "./providers";
import { Menu } from "@/components/Menu";
import { Separator } from "@/UI/components/ui/separator";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <QueryClientProvider>
          <Menu />
          <Separator className="mb-2" />
          {children}
        </QueryClientProvider>
        <Toaster />
      </body>
    </html>
  );
}
